version: '3'

services:
  database:
    image: 'mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
      - '3306'

  php:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8001:8000"
    depends_on:
      - database
    networks:
      - test_logiciel_network

volumes:
  database_data:

networks:
  test_logiciel_network:
    driver: bridge