version: '3'

services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8001:8000"
    depends_on:
      - database

  seeder:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    command: php bin/console doctrine:fixtures:load --no-interaction

  migration:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    command: php bin/console doctrine:migrations:migrate --no-interaction

  database:
    image: mariadb:10.7
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-test_logiciel}
      MARIADB_USER: ${MARIADB_USER:-test_user}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-test_password}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root_password}
    volumes:
      - database_data:/var/lib/mARIADB
    ports:
      - "3307:3306"

volumes:
  database_data: